title = "57° Raduno Nazionale Motoclub VVF Italia - Cosenza"
baseURL = "https://gaetano-pa.github.io/vvf-web/"
languageCode = "it"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "it"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.it]
    title = "57° Raduno Nazionale Motoclub VVF Italia - Cosenza"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = 'images/logo.png'
  site_logo = 'images/logo.png'
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  custom_css = ["css/custom.css"]
 
[[params.ananke_socials]]
      name = "facebook"
      url = "https://www.facebook.com/MotoclubVVFCS/"

